<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="kereddy-t460" name="com.tibco.rest.test.DataDrivenTestCases" tests="515" failures="19" timestamp="03 Dec 2020 05:30:55 GMT" time="563.574" errors="496">
  <testcase name="testcase" time="0.422" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.401" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.136" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.472" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.481" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.045" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.407" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.393" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.654" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.213" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.525" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.480" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.663" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.659" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Unable to store response string to variable or couldn&#039;t received response.">
      <![CDATA[java.lang.AssertionError: Unable to store response string to variable or couldn't received response.
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:415)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.272" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.113" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.888" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.412" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.444" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.393" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.336" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.474" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.524" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.346" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.757" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.518" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.401" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.294" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;RN Role Test you have entered  is already in use&quot; : Actual value is &quot;RN Role Test you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "RN Role Test you have entered  is already in use" : Actual value is "RN Role Test you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.458" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.498" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.398" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.369" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.272" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.489" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.557" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.504" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.534" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.435" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.834" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.807" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.897" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.015" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.407" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Admin Office  you have entered  is already in use&quot; : Actual value is &quot;Admin Office  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Admin Office  you have entered  is already in use" : Actual value is "Admin Office  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.208" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.954" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.586" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.341" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.736" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.561" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.402" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.640" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.489" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;The Transport name http_rn  you have entered  is already in use&quot; : Actual value is &quot;The Transport name http_rn  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "The Transport name http_rn  you have entered  is already in use" : Actual value is "The Transport name http_rn  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.476" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;EMAIL&quot; : Actual value is &quot;[&quot;EMAIL&quot;,&quot;FILE&quot;,&quot;FTP&quot;,&quot;HTTP&quot;]&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "EMAIL" : Actual value is "["EMAIL","FILE","FTP","HTTP"]"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.599" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.453" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.573" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.803" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.290" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.465" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.470" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.417" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.590" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.113" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.523" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.532" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.644" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.509" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.556" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.563" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.207" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.553" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.246" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.143" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.073" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.698" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.360" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.286" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.343" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.403" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.508" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.416" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.063" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.425" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.834" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.636" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.947" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.753" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.521" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.520" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.745" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.286" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.466" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.924" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.456" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.712" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.496" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.584" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.410" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.521" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.595" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.487" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.388" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.448" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.362" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.367" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.434" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.617" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.989" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.600" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.794" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.215" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Auto Domain Type  you have entered  is already in use&quot; : Actual value is &quot;Auto Domain Type  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Auto Domain Type  you have entered  is already in use" : Actual value is "Auto Domain Type  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.568" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.930" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.798" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.409" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.623" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.842" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.388" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.239" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.521" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.790" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.395" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.798" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.480" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.551" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;The Transport name https_rn  you have entered  is already in use&quot; : Actual value is &quot;The Transport name https_rn  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "The Transport name https_rn  you have entered  is already in use" : Actual value is "The Transport name https_rn  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.563" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.467" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.367" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.856" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.600" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.920" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.282" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.491" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.199" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.505" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.477" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.427" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.963" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.266" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.600" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.528" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;Domain Identity cannot have empty value.&quot; : Actual value is &quot;Domain Identity cannot have empty value&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "Domain Identity cannot have empty value." : Actual value is "Domain Identity cannot have empty value"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.478" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.406" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.474" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.332" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.694" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.512" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.503" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.565" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.599" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.603" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.431" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.384" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.279" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;ProxyHTTP you have entered  is already in use&quot; : Actual value is &quot;ProxyHTTP you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "ProxyHTTP you have entered  is already in use" : Actual value is "ProxyHTTP you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.252" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.475" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.950" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.384" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.348" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.109" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.904" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.542" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.272" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.438" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.390" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.523" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.217" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.359" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;ProxyHTTP1 you have entered  is already in use&quot; : Actual value is &quot;ProxyHTTP1 you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "ProxyHTTP1 you have entered  is already in use" : Actual value is "ProxyHTTP1 you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.462" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.551" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.433" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.364" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.817" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.406" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.757" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.489" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.512" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.491" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.640" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.418" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.462" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.644" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.510" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.407" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.910" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.452" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;false&quot; : Actual value is &quot;&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "false" : Actual value is ""
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.872" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should not be &quot;[]&quot; : Actual value is &quot;[]&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should not be "[]" : Actual value is "[]"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:344)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.403" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.380" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.168" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.481" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.672" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.479" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.430" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.546" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.549" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.682" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.413" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.368" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.650" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.479" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.617" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.081" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.382" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.162" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.737" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.589" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.438" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.558" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.464" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.858" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.389" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.016" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.418" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.362" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;TUESDAY,FRIDAY&quot; : Actual value is &quot;FRIDAY,TUESDAY&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "TUESDAY,FRIDAY" : Actual value is "FRIDAY,TUESDAY"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.404" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.527" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.535" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.597" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.478" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.247" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.381" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.387" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.436" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.460" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.662" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.209" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.451" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.594" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.394" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.468" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.431" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;true&quot; : Actual value is &quot;&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "true" : Actual value is ""
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.400" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.492" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.489" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.718" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.676" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.421" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.472" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.478" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.843" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.881" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.641" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.286" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.471" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.453" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.497" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.618" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.700" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.426" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.418" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.397" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.698" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.803" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.566" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.412" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.545" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.480" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.455" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.585" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.581" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.395" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.371" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.371" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.578" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.544" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.564" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.090" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.478" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.778" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.358" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.635" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.437" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.775" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.597" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.676" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.507" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.785" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.494" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.485" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.529" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.440" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.084" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.370" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.451" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.585" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.239" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.456" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.383" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.684" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.199" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.577" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.171" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.466" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.736" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.326" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.488" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.737" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.463" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.687" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.555" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.459" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.529" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.351" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.279" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.214" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.500" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.585" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.525" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.635" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.430" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.436" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.371" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.222" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.365" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.391" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.737" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.576" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.663" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.597" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.855" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.502" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.636" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.730" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.809" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.552" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.373" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.378" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.466" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.502" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.661" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.435" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.428" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.518" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.456" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.908" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.571" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.724" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.723" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.293" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.597" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.940" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.702" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.255" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.208" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.666" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.946" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.518" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.782" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.572" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.807" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.675" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.583" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.813" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.864" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.859" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.359" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.435" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.909" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.383" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.482" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.111" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.551" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.489" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.609" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.692" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.397" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.479" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.382" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.475" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.545" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.496" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.611" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.361" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.404" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.623" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.469" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.390" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.749" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.809" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.282" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.432" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.525" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.835" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.063" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.628" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.600" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.538" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.388" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Auto Role Edited  you have entered  is already in use&quot; : Actual value is &quot;Auto Role Edited  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Auto Role Edited  you have entered  is already in use" : Actual value is "Auto Role Edited  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.577" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.412" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;sccode1 you have entered  is already in use&quot; : Actual value is &quot;sccode1 you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "sccode1 you have entered  is already in use" : Actual value is "sccode1 you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.472" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.682" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.416" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.591" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.436" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.501" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.368" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.415" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.087" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.413" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.631" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.643" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.385" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.904" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.198" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Name  you have entered  is already in use&quot; : Actual value is &quot;Name  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Name  you have entered  is already in use" : Actual value is "Name  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.447" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.612" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.342" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.423" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.718" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.896" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.531" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.728" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.495" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.272" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.962" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.435" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.464" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.494" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.615" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.486" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.543" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.558" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.244" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.606" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.642" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.760" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.392" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.545" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.501" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.949" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.134" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.746" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.391" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.381" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.123" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.331" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.631" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.614" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.337" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.656" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.868" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.238" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.836" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.447" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.380" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.505" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.189" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.616" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.236" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.454" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.845" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.660" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.520" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.708" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.458" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.484" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.641" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.528" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.420" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.509" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.652" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.064" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.627" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.507" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.967" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.705" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.517" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.406" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.342" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.436" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.320" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.396" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.375" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.349" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.176" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;RosettaNet Role Name  you have entered  is already in use&quot; : Actual value is &quot;RosettaNet Role Name  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "RosettaNet Role Name  you have entered  is already in use" : Actual value is "RosettaNet Role Name  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.463" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.390" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.611" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.427" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.627" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.421" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.999" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.980" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.760" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.445" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.384" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.869" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.830" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.385" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.031" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.281" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.714" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.508" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.639" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.504" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.454" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.445" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.597" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.660" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.428" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.442" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.427" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.027" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.357" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.351" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;Groupname Auto User group  you have entered  is already in use.&quot; : Actual value is &quot;Groupname Auto User group  you have entered is already in use.&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "Groupname Auto User group  you have entered  is already in use." : Actual value is "Groupname Auto User group  you have entered is already in use."
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.467" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.718" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.519" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.471" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.887" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.276" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.407" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.522" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
</testsuite> <!-- com.tibco.rest.test.DataDrivenTestCases -->
