<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="kereddy-t460" name="com.tibco.rest.test.DataDrivenTestCases" tests="514" failures="19" timestamp="03 Dec 2020 06:26:42 GMT" time="573.835" errors="495">
  <testcase name="testcase" time="2.644" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.501" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.255" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Auto Domain Type  you have entered  is already in use&quot; : Actual value is &quot;Auto Domain Type  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Auto Domain Type  you have entered  is already in use" : Actual value is "Auto Domain Type  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.490" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.568" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.588" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.847" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.294" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.608" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.401" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.717" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.623" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.541" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.372" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;Groupname Auto User group  you have entered  is already in use.&quot; : Actual value is &quot;Groupname Auto User group  you have entered is already in use.&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "Groupname Auto User group  you have entered  is already in use." : Actual value is "Groupname Auto User group  you have entered is already in use."
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.422" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.730" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.270" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.410" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.431" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.486" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;The Transport name http_rn  you have entered  is already in use&quot; : Actual value is &quot;The Transport name http_rn  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "The Transport name http_rn  you have entered  is already in use" : Actual value is "The Transport name http_rn  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.377" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.455" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.605" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.704" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.463" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.882" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.862" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.656" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.580" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.200" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.420" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.916" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.436" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.215" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.618" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.432" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.530" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.350" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.616" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.278" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.168" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.691" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.263" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.411" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.850" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.490" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.531" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.697" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.246" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.051" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.382" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.399" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.954" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.434" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.422" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.043" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.675" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.645" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.493" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.485" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.337" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.535" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.627" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.490" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.660" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.424" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.948" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.390" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;TUESDAY,FRIDAY&quot; : Actual value is &quot;FRIDAY,TUESDAY&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "TUESDAY,FRIDAY" : Actual value is "FRIDAY,TUESDAY"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.419" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.499" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.533" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.369" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.589" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.587" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.599" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.432" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.474" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.721" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.489" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.317" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.932" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.734" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="4.154" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.493" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.437" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.842" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.540" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.223" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.343" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.511" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.638" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.713" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.508" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.676" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.864" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.571" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.548" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.370" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.326" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.510" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.515" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.483" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.500" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.935" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.560" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.899" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.512" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.474" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.519" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.657" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.730" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.551" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.615" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.427" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.715" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.304" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.446" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.543" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.610" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.433" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.209" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.666" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.715" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.347" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.804" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.486" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.630" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.396" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.509" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.696" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.431" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.440" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.372" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.573" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.695" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.561" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.487" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.637" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.417" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;EMAIL&quot; : Actual value is &quot;[&quot;EMAIL&quot;,&quot;FILE&quot;,&quot;FTP&quot;,&quot;HTTP&quot;]&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "EMAIL" : Actual value is "["EMAIL","FILE","FTP","HTTP"]"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.341" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.662" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.358" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.607" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.465" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.706" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.745" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.103" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.422" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.472" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.245" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.823" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.703" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.715" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.615" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.940" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.166" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.771" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.400" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.346" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.430" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.627" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.398" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.616" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.600" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.521" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.500" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.408" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.514" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.373" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.387" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.562" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.491" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.808" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.531" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.454" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;The Transport name https_rn  you have entered  is already in use&quot; : Actual value is &quot;The Transport name https_rn  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "The Transport name https_rn  you have entered  is already in use" : Actual value is "The Transport name https_rn  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.300" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.566" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.273" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.332" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.594" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.415" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.410" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.492" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.242" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should not be &quot;&quot; : Actual value is &quot;&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should not be "" : Actual value is ""
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.649" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.459" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.736" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.782" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.613" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.646" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.601" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.491" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.937" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.514" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.672" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.496" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.495" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.283" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;RosettaNet Role Name  you have entered  is already in use&quot; : Actual value is &quot;RosettaNet Role Name  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "RosettaNet Role Name  you have entered  is already in use" : Actual value is "RosettaNet Role Name  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.443" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.424" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.734" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.619" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.605" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.505" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.666" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.611" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.596" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.527" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.966" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.597" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.656" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.395" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.550" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.070" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.503" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.576" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.670" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.815" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.443" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.461" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.435" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.283" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.400" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.232" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Name  you have entered  is already in use&quot; : Actual value is &quot;Name  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Name  you have entered  is already in use" : Actual value is "Name  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.635" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.545" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;ProxyHTTP you have entered  is already in use&quot; : Actual value is &quot;ProxyHTTP you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "ProxyHTTP you have entered  is already in use" : Actual value is "ProxyHTTP you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.427" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.460" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.525" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.265" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.496" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.416" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.837" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.499" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.734" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.452" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.690" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.128" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.593" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.496" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.228" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.489" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.572" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.404" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.415" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.421" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.543" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.157" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.521" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.575" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.778" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.456" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.680" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.713" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="4.113" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.601" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Unable to store response string to variable or couldn&#039;t received response.">
      <![CDATA[java.lang.AssertionError: Unable to store response string to variable or couldn't received response.
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:415)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.495" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.434" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.489" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.755" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.762" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.643" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.662" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.514" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.595" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.631" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.369" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.310" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.532" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.554" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.254" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.423" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.390" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.616" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.520" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.045" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.412" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.979" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.404" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.545" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.427" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.702" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.143" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.010" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.528" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.670" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.331" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.784" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.523" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.850" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.460" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.513" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.729" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.215" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.422" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.363" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.442" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.717" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.490" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.964" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.562" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.423" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.333" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.882" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.800" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.669" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.685" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.789" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.773" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.806" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.531" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.587" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.393" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.710" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.115" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.650" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.252" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.467" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.387" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.502" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.606" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.410" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.424" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.431" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.633" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.415" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.019" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.420" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.001" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.293" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.622" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.787" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.120" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.482" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.475" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.498" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.400" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.288" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.785" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.621" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.306" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.989" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.401" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.470" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.442" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Auto Role Edited  you have entered  is already in use&quot; : Actual value is &quot;Auto Role Edited  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Auto Role Edited  you have entered  is already in use" : Actual value is "Auto Role Edited  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.400" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.599" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.677" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.625" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.495" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.635" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.994" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should not be &quot;[]&quot; : Actual value is &quot;[]&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should not be "[]" : Actual value is "[]"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertNotEquals(Assertions.java:196)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:520)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:344)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.663" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.507" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.376" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.748" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.410" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.641" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.676" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.391" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.569" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.538" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.754" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.515" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.080" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;RN Role Test you have entered  is already in use&quot; : Actual value is &quot;RN Role Test you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "RN Role Test you have entered  is already in use" : Actual value is "RN Role Test you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.809" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.460" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.483" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.510" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.448" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.827" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.717" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Admin Office  you have entered  is already in use&quot; : Actual value is &quot;Admin Office  you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Admin Office  you have entered  is already in use" : Actual value is "Admin Office  you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.934" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.418" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.841" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.652" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.376" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.633" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.528" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.090" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.967" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.412" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.370" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.831" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.396" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.589" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.554" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.640" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.258" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.532" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.446" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.693" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.709" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.633" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.562" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.546" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.478" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.168" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.553" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.044" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.692" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.537" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.367" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.375" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.595" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.422" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.774" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.301" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.422" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.417" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.755" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.460" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.618" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.629" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.425" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;Domain Identity cannot have empty value.&quot; : Actual value is &quot;Domain Identity cannot have empty value&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "Domain Identity cannot have empty value." : Actual value is "Domain Identity cannot have empty value"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.568" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.726" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.837" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.931" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.662" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.396" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.495" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.199" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.946" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.920" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.754" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.342" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;sccode1 you have entered  is already in use&quot; : Actual value is &quot;sccode1 you have entered  is already in use&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "sccode1 you have entered  is already in use" : Actual value is "sccode1 you have entered  is already in use"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:377)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.504" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.521" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.433" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.427" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.509" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.375" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.465" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.830" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.682" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.379" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.503" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.396" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.695" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.686" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should contains &quot;Proxy Servers  are set as default&quot; : Actual value is &quot;Proxy Servers  are set as default&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should contains "Proxy Servers  are set as default" : Actual value is "Proxy Servers  are set as default"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertContains(Assertions.java:212)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:533)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.523" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.242" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.411" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.537" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.996" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.480" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.722" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.551" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.999" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.630" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.548" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.514" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.513" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.644" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.310" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.766" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.835" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.513" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.636" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.389" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.114" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.365" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.657" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.247" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.483" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.595" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.483" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.612" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.555" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.548" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.481" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.993" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.730" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.574" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.561" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.500" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.388" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.632" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.373" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.591" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.808" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.481" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.403" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.347" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.016" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.573" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.750" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.444" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.525" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.423" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.502" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.264" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="3.433" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.501" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.646" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.603" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.415" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.578" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.385" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.467" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.425" classname="com.tibco.rest.test.DataDrivenTestCases">
    <failure type="java.lang.AssertionError" message="Expected value should be &quot;BCCE-3303&quot; : Actual value is &quot;BCCE-3100&quot;">
      <![CDATA[java.lang.AssertionError: Expected value should be "BCCE-3303" : Actual value is "BCCE-3100"
	at com.tibco.rest.restAssured.Assertions.assertTrue(Assertions.java:166)
	at com.tibco.rest.restAssured.Assertions.assertEquals(Assertions.java:183)
	at com.tibco.rest.test.DataDrivenTestCases.verifyResponse(DataDrivenTestCases.java:508)
	at com.tibco.rest.test.DataDrivenTestCases.testcase(DataDrivenTestCases.java:352)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.TestNG.privateMain(TestNG.java:1442)
	at org.testng.TestNG.main(TestNG.java:1411)
]]>
    </failure>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.535" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.441" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.348" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="2.572" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.632" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.639" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.482" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.447" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.503" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="1.007" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.480" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
  <testcase name="testcase" time="0.416" classname="com.tibco.rest.test.DataDrivenTestCases">
    <error/>
  </testcase> <!-- testcase -->
</testsuite> <!-- com.tibco.rest.test.DataDrivenTestCases -->
